### ISSUE TITLE
安装脚本设置磁盘时出错

### ISSUE THREAD

**Issue by a1768623020** [BaSierL/Arch_install#3]
选择swap文件时,无法输入文件大小值,只能选择输入no跳过才能进行到下一步,但是进行第二步会提示无法格式化swap文件,安装失败,
我记得以前可以选择跳过swap文件的生成来着.

**Comment by a1768623020** [comment]
选择4-2安装时报错如下
tee: /root/Temp_Data/Arch_install.log: No such file or directory
 ::==> Error code [23] Please input size: [example:512M-4G ~] !!!

**Comment by a1768623020** [comment]
Arch_install Script started
Arch_install 脚本已启动
     [1;37m***[0m [1;31mInstall System Module[0m [1;37m***[0m  
sda      8:0    0   100G  0 disk 
├─sda1   8:1    0     1G  0 part /mnt/boot
└─sda2   8:2    0    99G  0 part /mnt
sda      8:0    0   100G  0 disk 
├─sda1   8:1    0     1G  0 part /mnt/boot
└─sda2   8:2    0    99G  0 part /mnt
sda      8:0    0   100G  0 disk 
├─sda1   8:1    0     1G  0 part /mnt/boot
└─sda2   8:2    0    99G  0 part /mnt
mkfs.fat 4.1 (2017-01-24)
sda      8:0    0   100G  0 disk 
├─sda1   8:1    0     1G  0 part /mnt/boot
└─sda2   8:2    0    99G  0 part /mnt
[1;42m ::==>> Partition complete. [0m
 
Arch_install Script started
Arch_install 脚本已启动
     [1;37m***[0m [1;31mInstall System Module[0m [1;37m***[0m  
[1;42mUpdate the system clock.[0m
[1;32m ::==>[0m [1;32mInstall the base packages.[0m
[1;32m ::==>[0m  [1;32mConfigure Fstab File.[0m
[1;31m ::==>[0m [1;31mError code [23] Please input size: [example:512M-4G ~] !!! [0m

**Comment by BaSierL** [comment]
> 选择swap文件时，无法输入文件大小值，只能选择输入no跳过才能进行到下一步，但是进行第二步会提示无法格式化swap文件，安装失败，
> 我记得以前可以选择跳过swap文件的生成来着。

已解决

**Comment by BaSierL** [comment]
之前优化的时候，改动了，搞得用不了，而且没测试，网速太慢了
